import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Poppins } from 'next/font/google';
import { Overpass } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choose weights you need
});

const overpass = Overpass({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'], // choose weights you need
  variable: '--font-overpass',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${overpass.variable} h-full antialiased`}
    >
      <body
        className={`min-h-full flex flex-col ${poppins.className} ${overpass.className}`}
      >
        {children}
      </body>
    </html>
  );
}
